sut:
  build: .
  dockerfile: Dockerfile.test
  links:
    - mongo
app:
  build: .
  dockerfile: Dockerfile
  links:
    - mongo
mongo:
  container_name: mongo
  image: mongo
  volumes:
    - ./data:/data/db
  ports:
    - "27017:27017"
